apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep
  namespace: chirag
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar-injector-webhook.doofenshmirtz.me/inject: "yes"
      labels:
        app: sleep
    spec:
      containers:
      - name: sleep
        image: nginx
