kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sleep
  namespace: demo2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sleep
      annotations:
        sidecar-injector-webhook.doofenshmirtz.me/inject: "yes"
    spec:
      containers:
      - name: sleep
        image: tutum/curl
        command: ["/bin/sleep","infinity"]
        imagePullPolicy: IfNotPresent
