apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg-label
  labels:
    app: sidecar-injector
webhooks:
  - name: sidecar-injector.doofenshmirtz.me
    clientConfig:
      service:
        name: sidecar-injector-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1EUXdNakV3TWpRd05Wb1hEVEk1TURNek1URXdNalF3TlZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTNvClpHaXBjV3QvQ1ZWNTBUM3BuUGpiWFpIMWVvVy9YY2RhZDRwSDdDdC9wOWRYbHdMZ3g0NXRSSHU0M3dZOXlWNVMKc1BHOXVuM0RCZlorVVVlTTl2Y0hQZ0RGeGdnaFJNMnp4M3V6TmF2M2U0TXpEcGkrbTlDQ1JVVFVRelRXb21WSgpYL2xkcnRCcy9MVGhEVHlwK3hZdU0rZDEwSHBCQVF2dSt6K2lZeWJHaFdwS0dzRUYrdkJlYzRXYThFbXRKcjAvCjBYWjVoQXE0UlRSQm8xbDM1NElYN1UzVTRheElRTVY1RTlSd0lNVW8wMjVsc3VkS0dSUndWTDMwU1NGcWxJUE4KNlZhdEovQkNWRXdWTTloMGFkQktzL2xiYllGY0FQTUpkRWlUb3loc0dKUDJES2lrWks5VTdBRUFQZnNFMzh4MwoyVnNUT0dGZlBjczRheGZVdnowQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCVFVweWFyYkhLMzdGTkczS0xCVGluUkQ2aTd3MHhkbEZTU3ByaGVtbFZnUFRldmtMUwp6UWpkdFpPVVpRbFRXN3ZscHB3UDcrSUwrOENTazZFanhsT3hBM0FhMW1lQllTbTBZV3QxbkNQcjc0R2pCNzdUCjc3dkNlSXREckR2Y2NrN3VEbUJSR2h3a1JyaFJscExYQlhUOUJvNnRTZFM3cURqNWpRN3hnV1c2Qmd5SmwvYUQKdWhZSmF5TkxYT1YxMzR5dU1QbUdoaUliK2lOaHVzMU5qQ0k5ZmdHWW9zVHhZR1F2K05GbjdZd0hSMmovTUlWcQpxaEgwdmtDQmhRNlZrUWExdjEvSVoraXhYZkxmc3JDWU1hY1pzYXlIYXVzaUI1T2hrTE9JTFI5TXFKSVdya1d0Ck5Ca1RCNk1jalRZNGZhOEN1Y1ViaVE4RWpCaWhoYWR0ejBOTAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        sidecar-injector: enabled
